Repository Sylius/SyliusRector, pull requests merged in 2022-08, with the labels that each got.

#2 [Readme] Auto import names
  README.md
Labels: documentation

#5 Take into account rbac namespaces when upgrading to plus modular
  config/sets/sylius/plus/up-to-plus-modular.php
Labels: bug

#6 Add rules for multi source inventory plugin
  config/sets/sylius/plus/multi-source-inventory-plugin.php
  config/sets/sylius/plus/multi-store-plugin.php
  src/Set/SyliusPlus.php
  stubs/Sylius/Component/Core/Model/ProductVariant.php
  stubs/Sylius/Component/Core/Model/Shipment.php
  stubs/Sylius/MultiSourceInventoryPlugin/Domain/Model/ProductVariantInterface.php
  stubs/Sylius/MultiSourceInventoryPlugin/Domain/Model/ShipmentInterface.php
  tests/Set/SyliusPlus/MultiSourceInventoryPlugin/Fixture/class_extending_core_product_variant_model.php.inc
  tests/Set/SyliusPlus/MultiSourceInventoryPlugin/Fixture/class_extending_core_shipment_model.php.inc
  tests/Set/SyliusPlus/MultiSourceInventoryPlugin/MultiSourceInventoryPluginTest.php
  tests/Set/SyliusPlus/MultiSourceInventoryPlugin/config/configured_rule.php
Labels: Enhancement, DX

#12 New rules AliasTraitMethod and AddMethodCall...
  docs/rector_rules_overview.md
  src/NodeManipulator/TraitManipulator.php
  src/Rector/Class_/AddMethodCallToConstructorForClassesUsingTraitRector.php
  src/Rector/Dto/AddMethodCallToConstructorForClassesUsingTrait.php
  src/Rector/TraitUse/AliasTraitMethodRector.php
  stubs/Sylius/MultiStorePlugin/BusinessUnits/Domain/Model/BusinessUnitAwareTrait.php
  stubs/Sylius/MultiStorePlugin/CustomerPools/Domain/Model/CustomerPoolAwareTrait.php
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/AddMethodCallToConstructorForClassesUsingTraitTest.php
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/Fixture/class_with_constructor.php.inc
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/Fixture/class_with_constructor_and_the_same_method_call.php.inc
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/Fixture/class_with_two_traits.php.inc
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/Fixture/class_without_constructor.php.inc
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/config/configured_rule.php
  tests/Rector/TraitUse/AliasTraitMethod/AliasTraitMethodTest.php
  tests/Rector/TraitUse/AliasTraitMethod/Fixture/class_using_trait_with_already_existing_alias.php.inc
  tests/Rector/TraitUse/AliasTraitMethod/Fixture/class_using_trait_without_any_alias.php.inc
  tests/Rector/TraitUse/AliasTraitMethod/config/configured_rule.php
Labels: Feature
