Repository Sylius/SyliusRector, pull requests merged in 2022-11, with the labels that each got.

#15 [UpgradeModular] LastLoginIp class included in the rules
  config/sets/sylius/plus/up-to-plus-modular.php
Labels: Maintenance, Enhancement

#18 [UpgradeModular] More specific PartialShipping rewrite after extraction
  config/sets/sylius/plus/up-to-plus-modular.php
Labels: Bug

#19 [Maintenance] Rector version upgrade, static analysis included
  .github/workflows/tests.yaml
  composer.json
  config/config.php
  tests/Rector/Class_/AddInterfaceToClassExtendingType/AddInterfaceToClassExtendingTypeTest.php
  tests/Rector/Class_/AddMethodCallToConstructorForClassesUsingTrait/AddMethodCallToConstructorForClassesUsingTraitTest.php
  tests/Rector/Class_/AddTraitToClassExtendingType/AddTraitToClassExtendingTypeTest.php
  tests/Rector/TraitUse/AliasTraitMethod/AliasTraitMethodTest.php
  tests/Set/SyliusPlus/LoyaltyPlugin/MultiStorePluginTest.php
  tests/Set/SyliusPlus/MultiSourceInventoryPlugin/MultiSourceInventoryPluginTest.php
  tests/Set/SyliusPlus/MultiStorePlugin/MultiStorePluginTest.php
  tests/Set/SyliusPlus/PlusRbacPlugin/PlusRbacPluginTest.php
  tests/Set/SyliusPlus/ReturnPlugin/ReturnPluginTest.php
  tests/Set/UpgradeToPlusModular/MultiStorePluginTest.php
Labels: Maintenance
